[profile.default]
solc_version = "0.8.21"
src = "src"
out = "out"
libs = ["lib"]

[fmt]
bracket_spacing = true
line_length = 100
multiline_func_header = "all"
number_underscore="thousands"

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
